name: Release Tagger

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  update-previous-tags:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Update Previous Tags
        shell: bash
        run: |
          tag_ref="${{ github.ref }}"
          tag_ref="${tag_ref#*/}"

          echo "${tag_ref}"
